version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/go/src/app
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: gqlgen_password
      POSTGRES_USER: gqlgen_user
      POSTGRES_DB: gqlgen_db
    ports:
      - "5432:5432"