// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Category struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Item struct {
	ID       string    `json:"id"`
	Name     string    `json:"name"`
	Category *Category `json:"category"`
}
